apiVersion: v2
name: nexuscare-ai
description: A Helm chart for NexusCare AI Platform - Clinical and Insights AI Services
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - healthcare
  - ai
  - clinical-nlp
  - text-to-sql
  - rag

home: https://github.com/nexuscare/nexuscare-ai
sources:
  - https://github.com/nexuscare/nexuscare-ai

maintainers:
  - name: NexusCare Team
    email: team@nexuscare.ai

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    
  - name: qdrant
    version: "0.x.x"
    repository: https://qdrant.github.io/qdrant-helm
    condition: qdrant.enabled