[runpod]
name = "iaso-phi4"
gpu_type = "NVIDIA A40"
gpu_count = 1
container_disk_in_gb = 30
network_volume_size = 30

[environment]
MODEL_NAME = "microsoft/phi-4"
HF_TOKEN = "${HF_TOKEN}"
CACHE_DIR = "/runpod-volume/phi4-cache"

[build]
dockerfile = "Dockerfile"
context = "/phi4"