{{- if .Values.apiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexuscare-ai.fullname" . }}-api-gateway
  labels:
    {{- include "nexuscare-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  {{- if not .Values.apiGateway.autoscaling.enabled }}
  replicas: {{ .Values.apiGateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nexuscare-ai.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.apiGateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nexuscare-ai.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api-gateway
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nexuscare-ai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.apiGateway.podSecurityContext | nindent 8 }}
      containers:
        - name: api-gateway
          securityContext:
            {{- toYaml .Values.apiGateway.securityContext | nindent 12 }}
          image: {{ include "nexuscare-ai.image" (dict "repository" .Values.apiGateway.image.repository "tag" .Values.apiGateway.image.tag "Values" .Values "Chart" .Chart) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexuscare-ai.fullname" . }}-secrets
                  key: jwt-secret
            - name: CLINICAL_AI_URL
              value: "http://{{ include "nexuscare-ai.fullname" . }}-clinical-ai:8002"
            - name: TERMINOLOGY_URL
              value: "http://{{ include "nexuscare-ai.fullname" . }}-terminology:8001"
            - name: KNOWLEDGE_URL
              value: "http://{{ include "nexuscare-ai.fullname" . }}-knowledge:8004"
            - name: TEMPLATE_URL
              value: "http://{{ include "nexuscare-ai.fullname" . }}-template:8003"
            - name: SLM_URL
              value: "http://{{ include "nexuscare-ai.fullname" . }}-slm:8007"
            - name: IASOQL_URL
              value: "http://{{ include "nexuscare-ai.fullname" . }}-iasoql:8008"
            - name: EMBEDDINGS_URL
              value: "http://{{ include "nexuscare-ai.fullname" . }}-embeddings:8050"
            - name: QDRANT_URL
              value: "http://{{ include "nexuscare-ai.fullname" . }}-qdrant:6333"
            - name: REDIS_HOST
              value: {{ include "nexuscare-ai.redis.host" . }}
            - name: REDIS_PORT
              value: "6379"
            {{- if .Values.redis.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexuscare-ai.fullname" . }}-redis
                  key: redis-password
            {{- end }}
            - name: ALLOWED_ORIGINS
              value: {{ .Values.apiGateway.env.ALLOWED_ORIGINS | quote }}
            - name: RATE_LIMIT
              value: {{ .Values.apiGateway.env.RATE_LIMIT | quote }}
            {{- range $key, $value := .Values.apiGateway.env }}
            {{- if not (has $key (list "ALLOWED_ORIGINS" "RATE_LIMIT")) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
      {{- with .Values.apiGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}