version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: iaso-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - iaso-network

  # Optional: Qdrant Web UI
  qdrant-ui:
    image: qdrant/qdrant-web-ui:latest
    container_name: iaso-qdrant-ui
    ports:
      - "6335:6335"
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    networks:
      - iaso-network

networks:
  iaso-network:
    driver: bridge