apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-action-server
  namespace: iasovoice
  labels:
    app: rasa-action-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rasa-action-server
  template:
    metadata:
      labels:
        app: rasa-action-server
    spec:
      containers:
      - name: action-server
        image: iaso/rasa-actions-medical:latest  # You'll build this
        ports:
        - containerPort: 5055
          name: http
        env:
        - name: CLINICAL_AI_URL
          value: "http://clinical-ai-service.default.svc.cluster.local:8002"
        - name: APPOINTMENT_SERVICE_URL
          value: "http://appointment-service.default.svc.cluster.local:8080"
        - name: PHI4_MCP_URL
          value: "http://phi4-mcp.iasovoice.svc.cluster.local:8090"
        - name: RUNPOD_API_KEY
          valueFrom:
            secretKeyRef:
              name: runpod-secret
              key: api-key
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 5055
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5055
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-action-server
  namespace: iasovoice
  labels:
    app: rasa-action-server
spec:
  selector:
    app: rasa-action-server
  ports:
  - port: 5055
    targetPort: 5055
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rasa-action-server-hpa
  namespace: iasovoice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rasa-action-server
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80