apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: iaso-chat
  namespace: iaso-chat

resources:
  - namespace.yaml
  - configmap.yaml
  - redis-deployment.yaml
  - rasa-server-deployment.yaml
  - rasa-actions-deployment.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: iaso-chat
  app.kubernetes.io/part-of: iaso-platform
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  deployment.kubernetes.io/revision: "1"
  
# Image replacements (will be updated by CI/CD)
images:
  - name: rasa/rasa
    newTag: "3.6.0"
  - name: iaso/rasa-actions-medical
    newName: 727646479986.dkr.ecr.us-west-2.amazonaws.com/iaso/rasa-actions-medical
    newTag: latest
  - name: iaso/rasa-mcp
    newName: 727646479986.dkr.ecr.us-west-2.amazonaws.com/iaso/rasa-mcp
    newTag: latest

# Resource patches for different environments
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rasa-server
      namespace: iaso-chat
    spec:
      template:
        spec:
          containers:
          - name: rasa-server
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1"

# Configuration for different environments
configurations:
  - name: production
    commonLabels:
      environment: production
    replicas:
      - name: rasa-server
        count: 3
      - name: rasa-action-server
        count: 3
      - name: rasa-mcp-server
        count: 2
  
  - name: staging
    commonLabels:
      environment: staging
    replicas:
      - name: rasa-server
        count: 2
      - name: rasa-action-server
        count: 2
      - name: rasa-mcp-server
        count: 1
  
  - name: development
    commonLabels:
      environment: development
    replicas:
      - name: rasa-server
        count: 1
      - name: rasa-action-server
        count: 1
      - name: rasa-mcp-server
        count: 1