apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-action-server
  namespace: iaso-chat
  labels:
    app: rasa-action-server
    component: actions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rasa-action-server
  template:
    metadata:
      labels:
        app: rasa-action-server
        component: actions
    spec:
      containers:
      - name: action-server
        image: iaso/rasa-actions-medical:latest
        ports:
        - containerPort: 5055
          name: http
        env:
        - name: RUNPOD_API_KEY
          valueFrom:
            secretKeyRef:
              name: runpod-secret
              key: api-key
        - name: WHISPER_ENDPOINT_ID
          value: "rntxttrdl8uv3i"
        - name: PHI4_ENDPOINT_ID
          value: "tmmwa4q8ax5sg4"
        - name: CLINICAL_AI_URL
          value: "http://clinical-ai-service:8002"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 5055
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5055
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 10"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-action-server
  namespace: iaso-chat
  labels:
    app: rasa-action-server
    component: actions
spec:
  selector:
    app: rasa-action-server
  ports:
  - port: 5055
    targetPort: 5055
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: runpod-secret
  namespace: iaso-chat
type: Opaque
stringData:
  api-key: "your-runpod-api-key-here"  # Change this!
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rasa-action-server-pdb
  namespace: iaso-chat
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: rasa-action-server