apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-server
  namespace: iaso-chat
  labels:
    app: rasa-server
    component: nlu-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rasa-server
  template:
    metadata:
      labels:
        app: rasa-server
        component: nlu-core
    spec:
      containers:
      - name: rasa-server
        image: rasa/rasa:3.6.0
        ports:
        - containerPort: 5005
          name: http
        env:
        - name: RASA_ENVIRONMENT
          value: "production"
        - name: RASA_CORS_ORIGINS
          value: "*"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        command:
        - rasa
        - run
        - --enable-api
        - --cors
        - "*"
        - --port
        - "5005"
        - --endpoints
        - endpoints.yml
        - --credentials
        - credentials.yml
        - --debug
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: rasa-config
          mountPath: /app/config.yml
          subPath: config.yml
        - name: rasa-config
          mountPath: /app/domain.yml
          subPath: domain.yml
        - name: rasa-config
          mountPath: /app/endpoints.yml
          subPath: endpoints.yml
        - name: rasa-config
          mountPath: /app/credentials.yml
          subPath: credentials.yml
        - name: rasa-data
          mountPath: /app/data
        - name: rasa-models
          mountPath: /app/models
        livenessProbe:
          httpGet:
            path: /status
            port: 5005
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 5005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 15"
      volumes:
      - name: rasa-config
        configMap:
          name: rasa-config
      - name: rasa-data
        configMap:
          name: rasa-training-data
      - name: rasa-models
        persistentVolumeClaim:
          claimName: rasa-models-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-server
  namespace: iaso-chat
  labels:
    app: rasa-server
    component: nlu-core
spec:
  selector:
    app: rasa-server
  ports:
  - port: 5005
    targetPort: 5005
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rasa-models-pvc
  namespace: iaso-chat
  labels:
    app: rasa-server
    component: nlu-core
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rasa-server-pdb
  namespace: iaso-chat
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: rasa-server