apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-session-store
  namespace: iaso-chat
  labels:
    app: redis-session-store
    component: session-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-session-store
  template:
    metadata:
      labels:
        app: redis-session-store
        component: session-store
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        - --appendonly
        - "yes"
        - --maxmemory
        - "256mb"
        - --maxmemory-policy
        - "allkeys-lru"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-session-store
  namespace: iaso-chat
  labels:
    app: redis-session-store
    component: session-store
spec:
  selector:
    app: redis-session-store
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: iaso-chat
  labels:
    app: redis-session-store
    component: session-store
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: iaso-chat
type: Opaque
stringData:
  password: "change-this-secure-password"  # Change this!